name = "youtube-data-api-webhook"
main = "src/index.ts"
compatibility_date = "2023-12-18"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/r2/api/workers/workers-api-usage/
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "youtube-data-api-notifications"